/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-06-05 06:40:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setAttribute("siteTitle", "폼 레이아웃");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./include/css/mainstyle.css\">\r\n");
      out.write("<!-- 본문 타이틀(그냥 아무거나) -->\r\n");
      out.write("<h2>폼 레이아웃</h2>\r\n");
      out.write("\r\n");
      out.write("<!-- 폼 박스 50% 사이즈(작은 폼) -->\r\n");
      out.write("<div class=\"formbox formbox_50\">\r\n");
      out.write("\t<div class=\"formcontent\">\r\n");
      out.write("\t\t폼박스 크기 50% (소형)\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 폼 박스 75% 사이즈(중간 사이즈 폼) -->\r\n");
      out.write("<div class=\"formbox formbox_75\">\r\n");
      out.write("\t<div class=\"formcontent\">\r\n");
      out.write("\t\t폼박스 크기 75% (중형)\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 폼 박스 100% 사이즈 -->\r\n");
      out.write("<div class=\"formbox formbox_100\">\r\n");
      out.write("\t<div class=\"formcontent\">\r\n");
      out.write("\t\t폼박스 크기 100% (대형)\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 사용예 -->\r\n");
      out.write("<div class=\"formbox formbox_75\">\r\n");
      out.write("\t<!-- 타이틀(그냥 아무거나) -->\r\n");
      out.write("\t<h3>사용예</h3>\r\n");
      out.write("\t<div class=\"formcontent\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<!-- 텍스트 필드 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"someID1\" class=\"rowlabel\">텍스트1</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID1\" class=\"sitetxt form_ele_100\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- form_ele_ 클래스를 통해 사이즈 조절 가능 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"someID2\" class=\"rowlabel\">텍스트2</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID2\" class=\"sitetxt form_ele_50\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 사이즈는 4개(가로 20%, 30%, 50%, 100%) -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"someID3\" class=\"rowlabel\">텍스트3</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID3\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 한줄마다 formrow클래스를 적용한 div필요함 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"someID4\" class=\"rowlabel\">텍스트4</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID4\" class=\"sitetxt form_ele_20\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 한줄에 여러개의 폼요소 사용가능 -->\r\n");
      out.write("\t\t\t<!-- form_ele_ 뒤의 숫자 합계가 100을 넘으면 안됨 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">전화</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID5\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">-</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID6\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">-</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID7\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 폼요소들 사이에 구분을 위한 한글자가 필요하다면 \r\n");
      out.write("\t\t\t\tform_ele_onechar클래스를 적용한 span태그 사용 -->\r\n");
      out.write("\t\t\t<!-- form_ele_ 뒤의 숫자 합계 계산시 \r\n");
      out.write("\t\t\t\tform_ele_onechar하나당 숫자 5를 차지한다고 보고 계산 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">이메일</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID8\" class=\"sitetxt form_ele_40\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">@</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"someID9\" class=\"sitetxt form_ele_50\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 라디오버튼 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">라디오 버튼</label>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"btnradio1\" name=\"radiobtn\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnradio1\">버튼1</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"btnradio2\" name=\"radiobtn\" value=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnradio2\">버튼2</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"btnradio3\" name=\"radiobtn\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnradio3\">버튼3</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 체크박스 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">체크박스</label>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk1\" name=\"chkbtn\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk1\">박스1</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk2\" name=\"chkbtn\" value=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk2\">박스2</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk3\" name=\"chkbtn\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk3\">박스3</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk4\" name=\"chkbtn\" value=\"4\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk4\">박스4</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk5\" name=\"chkbtn\" value=\"5\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk5\">박스5</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 드롭박스(select) -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\" for=\"selbox1\">드롭박스(select)</label>\r\n");
      out.write("\t\t\t\t<select id=\"selbox1\" name=\"selbox1\" class=\"siteselect form_ele_100\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">하나</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">둘</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">셋</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">넷</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">다섯</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 텍스트 필드가 아니라도 form_ele_50클래스를 지정하면 길이조절가능 -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\" for=\"selbox2\">드롭박스(절반길이)</label>\r\n");
      out.write("\t\t\t\t<select id=\"selbox2\" name=\"selbox2\" class=\"siteselect form_ele_50\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">하나</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">둘</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">셋</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">넷</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">다섯</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 텍스트 Area -->\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\" for=\"areabox\">텍스트 Area</label>\r\n");
      out.write("\t\t\t\t<textarea id=\"areabox\" name=\"areabox\" class=\"sitetxt form_ele_100\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow formrow_center\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입\" class=\"sitebtn\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 사용예(탭 + 폼) -->\r\n");
      out.write("<div class=\"formbox formbox_50\">\r\n");
      out.write("\t<h3>사용예(탭 + 폼)</h3>\r\n");
      out.write("\t<!-- 탭 -->\r\n");
      out.write("\t<div class=\"formtab\">\r\n");
      out.write("\t\t<div class=\"tabbtn tabbtn_3 tabsaja tabbtn_sel\">사자</div>\r\n");
      out.write("\t\t<div class=\"tabbtn tabbtn_3 tabpanda\">\r\n");
      out.write("\t\t\t<a href=\"#링크\">판다</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tabbtn tabbtn_3\">\r\n");
      out.write("\t\t\t<a href=\"#링크\">경매</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 폼 -->\r\n");
      out.write("\t<div class=\"formcontent\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"otherID1\" class=\"rowlabel\">텍스트1</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID1\" class=\"sitetxt form_ele_100\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"otherID2\" class=\"rowlabel\">텍스트2</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID2\" class=\"sitetxt form_ele_50\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"otherID3\" class=\"rowlabel\">텍스트3</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID3\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label for=\"otherID4\" class=\"rowlabel\">텍스트4</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID4\" class=\"sitetxt form_ele_20\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">전화</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID5\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">-</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID6\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">-</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID7\" class=\"sitetxt form_ele_30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">이메일</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"sotherID8\" class=\"sitetxt form_ele_40\">\r\n");
      out.write("\t\t\t\t<span class=\"form_ele_onechar\">@</span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"otherID9\" class=\"sitetxt form_ele_50\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">라디오 버튼</label>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"otherradio1\" name=\"radiobtn\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherradio1\">버튼1</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"otherradio2\" name=\"radiobtn\" value=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherradio2\">버튼2</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_30\">\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"otherradio3\" name=\"radiobtn\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherradio3\">버튼3</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\">체크박스</label>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"otherchk1\" name=\"chkbtn\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherchk1\">박스1</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"otherchk2\" name=\"chkbtn\" value=\"2\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherchk2\">박스2</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"otherchk3\" name=\"chkbtn\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherchk3\">박스3</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"otherchk4\" name=\"chkbtn\" value=\"4\">\r\n");
      out.write("\t\t\t\t\t<label for=\"otherchk4\">박스4</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form_ele_20\">\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"btnchk5\" name=\"chkbtn\" value=\"5\">\r\n");
      out.write("\t\t\t\t\t<label for=\"btnchk5\">박스5</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\" for=\"othersel1\">드롭박스(select)</label>\r\n");
      out.write("\t\t\t\t<select id=\"othersel1\" name=\"selbox1\" class=\"siteselect form_ele_100\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">하나</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">둘</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">셋</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">넷</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">다섯</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow\">\r\n");
      out.write("\t\t\t\t<label class=\"rowlabel\" for=\"othersel2\">드롭박스(절반길이)</label>\r\n");
      out.write("\t\t\t\t<select id=\"othersel2\" name=\"selbox2\" class=\"siteselect form_ele_50\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">하나</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">둘</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">셋</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">넷</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">다섯</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"formrow formrow_center\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입\" class=\"sitebtn\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
