/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-06-05 08:57:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.general;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spw.general.vo.GeneralVO;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpSession;

public final class generalDetailForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/main/top2.jsp", Long.valueOf(1622109146243L));
    _jspx_dependants.put("/WEB-INF/view/main/top1.jsp", Long.valueOf(1621935771264L));
    _jspx_dependants.put("/WEB-INF/view/main/bottom.jsp", Long.valueOf(1621935771214L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.spw.general.vo.GeneralVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setAttribute("siteTitle", "상세보기");

      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');

	// 타이틀 설정
	String siteTitle = "사자판다";

	String siteTitleParam = (String)request.getAttribute("siteTitle");

	if(siteTitleParam != null && siteTitleParam.length() > 0){
		siteTitle = siteTitleParam;
	}
	HttpSession hs =request.getSession();
	String sessionNum = (String)hs.getAttribute("mnum");
	//System.out.println("세션 회원번호 : "+sessionNum);

      out.write("\n");
      out.write("<!-- 버튼, 메뉴, 하단바, 검색창 색상은 아직 안정해짐 -->\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>");
      out.print(siteTitle );
      out.write("</title>\n");
      out.write("<link rel=\"shortcut icon\" href=\"/spw/include/img/favicon.ico\">\n");
      out.write("<link rel=\"icon\" href=\"/spw/include/img/favicon.ico\">\n");
      out.write("<script type=\"text/javascript\" src=\"/spw/include/js/jquery-1.12.0.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/calendar_datepicker/jquery-ui-1.12.1/jquery-ui.min.css\">\n");
      out.write("<script src=\"/spw/calendar_datepicker/jquery-ui-1.12.1/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"/spw/calendar_datepicker/jquery-ui-1.12.1/datepicker-ko.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/include/css/dimlayer.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/include/css/mainbaner.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/include/css/login.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/include/css/mainstyle.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/spw/include/css/memberinsert.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t/* 거래신청 */\r\n");
      out.write("\t\t$('.deal-btn').click(function(){\r\n");
      out.write("\t\t\t//alert(\"gd\");\r\n");
      out.write("\t    \tvar mnum = \"");
      out.print(sessionNum);
      out.write("\";\r\n");
      out.write("\t    \t//alert(mnum);\r\n");
      out.write("\t       \t//alert(mnum.length);\r\n");
      out.write("\t    \tif(mnum!=null&&mnum.length>4){\r\n");
      out.write("\t    \t\tvar $id = $(this).attr('id');\r\n");
      out.write("\t\t        var id = '#'+$id+'Layer';\r\n");
      out.write("\t\t        //alert(id);\r\n");
      out.write("\t\t        layer_popup(id);\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\talert(\"로그인하세요.\");\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 레이어팝업 생성.\r\n");
      out.write("\t    function layer_popup(el){\r\n");
      out.write("\t        var $el = $(el);        //레이어의 id를 $el 변수에 저장\r\n");
      out.write("\t        // prev() - 이전요소를 선택하도록 반환. \r\n");
      out.write("\t        // hasClass() - 클래스가 있냐 없냐?\r\n");
      out.write("       \t\t//dimmed 레이어를 감지하기 위한 boolean 변수\r\n");
      out.write("\t        var isDim = $el.prev().hasClass('dimBg');\r\n");
      out.write("\t        \r\n");
      out.write("\t        //alert(isDim);\r\n");
      out.write("\t        // true 일경우 .dim-layer을 페이드인 아닐경우 $el을 페이드인.\r\n");
      out.write("\t        // 링크를 페이드인 하거나 아님 클래스를 페이드인.\r\n");
      out.write("\t        isDim ? $('.dim-layer').fadeIn() : $el.fadeIn();\r\n");
      out.write("\t        \r\n");
      out.write("\t        var $elWidth = ~~($el.outerWidth()),\r\n");
      out.write("\t            $elHeight = ~~($el.outerHeight()),\r\n");
      out.write("\t            docWidth = $(document).width(), \r\n");
      out.write("\t            docHeight = $(document).height();\r\n");
      out.write("\t\t\t//alert($elWidth);\r\n");
      out.write("\t\t\t//alert($elHeight);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        // 화면의 중앙에 레이어를 띄운다.\r\n");
      out.write("\t        if ($elHeight < docHeight || $elWidth < docWidth) {\r\n");
      out.write("\t            $el.css({\r\n");
      out.write("\t                marginTop: -$elHeight /2,\r\n");
      out.write("\t                marginLeft: -$elWidth/2\r\n");
      out.write("\t            })\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            $el.css({top: 0, left: 0});\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("\t        $el.find('.btn-layerClose').click(function(){\r\n");
      out.write("\t            isDim ? $('.dim-layer').fadeOut() : $el.fadeOut(); // 닫기 버튼을 클릭하면 레이어가 닫힌다.\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        });\r\n");
      out.write("\r\n");
      out.write("\t        $('.layer .dimBg').click(function(){\r\n");
      out.write("\t            $('.dim-layer').fadeOut();\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        });\r\n");
      out.write("\r\n");
      out.write("\t    }\r\n");
      out.write("\t    // 거래 전송버튼.\r\n");
      out.write("\t    $('#dealFunc').click(function(){\r\n");
      out.write("\t    \t//alert(\"전송\");\r\n");
      out.write("\t\t    $(\"#detailList\").attr(\"action\", \"/spw/dealInsert.spw\");\t    \t\t\r\n");
      out.write("\t\t\t$(\"#detailList\").submit();\t    \t\t\r\n");
      out.write("\t    });\r\n");
      out.write("\t   \r\n");
      out.write("\t    // 찜하기.\r\n");
      out.write("\t    $('#pick').click(function(){\r\n");
      out.write("\t    \t//alert(\"찜하기\");\r\n");
      out.write("\t    \tvar mnum = \"");
      out.print(sessionNum);
      out.write("\";\r\n");
      out.write("\t    \tif(mnum!=null&&mnum.length>4){\r\n");
      out.write("\t    \t\tvar gnum = $(\"#gnum\").val();\r\n");
      out.write("\t    \t \t$(\"#detailList\").attr(\"action\", \"/spw/myPick.spw?gnum\"+gnum);\r\n");
      out.write("\t\t\t\t$(\"#detailList\").submit();\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\talert(\"로그인하세요.\");\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\r\n");
      out.write("\t/*\t수정 클릭 : generalUpdateForm */\r\n");
      out.write("\tfunction generalUpdateForm(){\r\n");
      out.write("\t\tvar gnum = $(\"#gnum\").val();\r\n");
      out.write("\t\t//alert(\"gnum >> \" + gnum);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#gnum\").val(gnum);\r\n");
      out.write("\t\t$(\"#detailList\").attr(\"action\", \"generalUpdateForm.spw\");\r\n");
      out.write("\t\t$(\"#detailList\").submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t/* 삭제 클릭 : generalDeleteOK */\r\n");
      out.write("\tfunction generalDeleteOK(){\r\n");
      out.write("\t\t//alert(\"generalDeleteOK : 삭제 함수 시작\");\r\n");
      out.write("\t\tconsole.log(\"generalDeleteOK : 삭제 함수 시작\");\r\n");
      out.write("\t\t$(\"#detailList\").attr(\"action\", \"generalDeleteOK.spw\");\r\n");
      out.write("\t\t$(\"#detailList\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 취소 클릭 : cancel() */\r\n");
      out.write("\tfunction cancel(){\r\n");
      out.write("\t\t//alert(\"cancel : 목록으로\")\r\n");
      out.write("\t\tconsole.log(\"cancel : 취소 함수 시작\")\r\n");
      out.write("\t\thistory.back();\r\n");
      out.write("\t\t/* location.href=\"generalAllList.spw\"; */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 상단바와 내용 -->\r\n");
      out.write("<div id=\"sitearea\">\r\n");
      out.write("\t<!-- 상단바 -->\r\n");
      out.write("\t<header id=\"topbar\">\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t<!-- 상단바 로고영역(로고, 검색) -->\r\n");
      out.write("\t\t\t<div id=\"logoarea\">\r\n");
      out.write("\t\t\t\t<!-- 로고 -->\r\n");
      out.write("\t\t\t\t<div id=\"toplogo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/index.spw\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/spw/include/img/logo.png\" id=\"sitelogo\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"mobilebtns\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"◎\" class=\"sitebtn\" id=\"btnSearchBar\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"●\" class=\"sitebtn\" id=\"btnBtnArea\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"▤\" class=\"sitebtn\" id=\"btnNaviArea\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 검색바 -->\r\n");
      out.write("\t\t\t\t<div id=\"searchbar\">\r\n");

	String topSearchText = "";
	String topAtitle = request.getParameter("atitle");
	String topGtitle = request.getParameter("gtitle");

	if(topGtitle != null && topGtitle.length() > 0){
		topSearchText = topGtitle;
	}else if(topAtitle != null && topAtitle.length() > 0){
		topSearchText = topAtitle;
	}

      out.write("\r\n");
      out.write("\t<form method=\"GET\" id=\"topSearchform\">\r\n");
      out.write("\t\t<!-- 드롭다운 -->\r\n");
      out.write("\t\t<select id=\"topSearchsel\">\r\n");
      out.write("\t\t\t<option value=\"1\">사자</option>\r\n");
      out.write("\t\t\t<option value=\"2\">판다</option>\r\n");
      out.write("\t\t\t<option value=\"3\">경매</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<!-- 텍스트필드 -->\r\n");
      out.write("\t\t<div id=\"searchtext\">\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"topSearchtxt\" value=\"");
      out.print(topSearchText );
      out.write("\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 검색버튼 -->\r\n");
      out.write("\t\t<input type=\"submit\" value=\"검색\" id=\"searchbtn\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t$(\"form#topSearchform\").submit(function(){\r\n");
      out.write("\t\t\t\t// 폼\r\n");
      out.write("\t\t\t\tvar topSearchform = $(\"form#topSearchform\")\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 셀렉트\r\n");
      out.write("\t\t\t\tvar topSearchSel = $(\"#topSearchsel\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 텍스트\r\n");
      out.write("\t\t\t\tvar topSearchtxt = $(\"#topSearchtxt\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(topSearchtxt.val() != null && topSearchtxt.val() != \"\"){\r\n");
      out.write("\t\t\t\t\t// 셀렉트 내용\r\n");
      out.write("\t\t\t\t\tvar selectVal = topSearchSel.val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif(selectVal == \"3\"){\r\n");
      out.write("\t\t\t\t\t\t// 경매\r\n");
      out.write("\t\t\t\t\t\t// 텍스트필드 name속성 지정\r\n");
      out.write("\t\t\t\t\t\ttopSearchtxt.attr(\"name\", \"atitle\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 경로지정\r\n");
      out.write("\t\t\t\t\t\ttopSearchform.attr(\"action\", \"/spw/auctionList.spw\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 전송\r\n");
      out.write("\t\t\t\t\t\ttopSearchform.submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t// 텍스트필드 name속성 지정\r\n");
      out.write("\t\t\t\t\t\ttopSearchtxt.attr(\"name\", \"gtitle\");\r\n");
      out.write("\t\t\t\t\t\tif(selectVal == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t// 사자\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 경로지정\r\n");
      out.write("\t\t\t\t\t\t\ttopSearchform.attr(\"action\", \"/spw/generalSList.spw\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 전송\r\n");
      out.write("\t\t\t\t\t\t\ttopSearchform.submit();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else if(selectVal == \"2\"){\r\n");
      out.write("\t\t\t\t\t\t\t// 판다\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 경로지정\r\n");
      out.write("\t\t\t\t\t\t\ttopSearchform.attr(\"action\", \"/spw/generalPList.spw\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 전송\r\n");
      out.write("\t\t\t\t\t\t\ttopSearchform.submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"검색어를 입력해 주세요\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#btnSearchBar\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#searchbar\").css(\"display\") == \"none\"){\r\n");
      out.write("\t\t\t\t\t$(\"#btnarea\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#naviarea\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#searchbar\").slideDown(200);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#searchbar\").slideUp(200);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#btnBtnArea\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#btnarea\").css(\"display\") == \"none\"){\r\n");
      out.write("\t\t\t\t\t$(\"#searchbar\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#naviarea\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#btnarea\").slideDown(200);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#btnarea\").slideUp(200);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#btnNaviArea\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#naviarea\").css(\"display\") == \"none\"){\r\n");
      out.write("\t\t\t\t\t$(\"#searchbar\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#btnarea\").slideUp(100);\r\n");
      out.write("\t\t\t\t\t$(\"#naviarea\").slideDown(200);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#naviarea\").slideUp(200);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"btnarea\">\r\n");

	HttpSession hs2 =request.getSession();
	String sessionNum2 = (String)hs2.getAttribute("mnum");
	System.out.println("세션 회원번호 : "+sessionNum2);

      out.write('\r');
      out.write('\n');
				
					
				String admin="M202007300001";
				if(sessionNum2!=null&&sessionNum2.length()>0){
					if(admin.equals(sessionNum2)){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/spw/logout.spw\" class=\"sitebtn\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/spw/adminSelectAll.spw\" class=\"sitebtn\">관리자페이지</a> \r\n");
					
					}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/spw/logout.spw\" class=\"sitebtn\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/spw/myPage.spw\" class=\"sitebtn\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/spw/generalInsertForm.spw\" class=\"sitebtn\">글쓰기</a>\r\n");
					
					}
				}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/loginform.spw\" class=\"sitebtn\">로그인</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/meminsertform.spw\" class=\"sitebtn\">회원가입</a>\r\n");

				}

      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 메뉴 -->\r\n");
      out.write("\t\t<div id=\"naviarea\">\r\n");
      out.write("\t\t\t<ul class=\"wrapper\">\r\n");
      out.write("\t\t\t\t<!-- 메뉴버튼들 -->\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/generalSList.spw\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t사자\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/generalPList.spw\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t판다\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/local.spw\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t동네\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"/spw/auctionList.spw\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t경매\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- 내용 -->\r\n");
      out.write(" \t<div id=\"sitecontent\">\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	// Controller에서 setAttribute 세팅 값을 받아온다.
	Object obj = request.getAttribute("detailDate");
	System.out.println("obj >> " + obj);
	if(obj != null){
			GeneralVO gvo = (GeneralVO)obj;
			String gsort = gvo.getGsort();

      out.write("\r\n");
      out.write("<form id=\"detailList\" name=\"detailList\" method=\"POST\" >\r\n");
      out.write("<div class=\"product_detail\">\r\n");
      out.write("\t<div class=\"product_top\">\r\n");
      out.write("\t\t<h2 class=\"product_title\">\r\n");
      out.write("\t\t\t");
      out.print(gvo.getGtitle() );
      out.write("\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<div class=\"product_info_mini\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<span class=\"product_writer\">\r\n");
      out.write("\t\t\t\t아이디 : ");
      out.print(gvo.getMid() );
      out.write(" \r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<span class=\"product_date\">\r\n");
      out.write("\t\t\t\t(");
      out.print(gvo.getGregdate() );
      out.write(")\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 이미지 -->\r\n");
      out.write("\t\t<!-- product_info_images의 style와 내부의 img태그의 src에 동일한 이미지 경로 입력 -->\r\n");
      out.write("\t\t<div class=\"product_info_images\" style=\"background-image: url('/spw/uploadImages/");
      out.print(gvo.getGphoto());
      out.write("');\" alt=\"상품 이미지\">\r\n");
      out.write("\t\t\t<img src=\"/spw/uploadImages/");
      out.print(gvo.getGphoto() );
      out.write("\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"product_info_side\">\r\n");

			if(gsort.equals("1")){

      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"product_sort_label label_saja\">사자</div>\r\n");

			}else{

      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"product_sort_label label_panda\">판다</div>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t<div class=\"product_info_detail\">\r\n");
      out.write("\t\t\t\t<p>카테고리 : <span>");
      out.print(gvo.getCgname() );
      out.write("</span></p>\r\n");
      out.write("\t\t\t\t<p>거래지역 : <span>");
      out.print(gvo.getGloc() );
      out.write("</span></p>\r\n");

				String status = gvo.getGstatus();
				String str="";
				if(status.equals("1")){
					str="거래중";
				}
				if(status.equals("2")){
					str="거래완료";
				}
				if(status.equals("3")){
					str="거래취소";
				}

      out.write("\r\n");
      out.write("\t\t\t\t<p>거래상태 : <span>");
      out.print(str );
      out.write("</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"product_info_bottom\">\r\n");
      out.write("\t\t\t\t<div class=\"product_info_price\">\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gvo.getGprice() );
      out.write("</span>원\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"product_action\">\r\n");
      out.write("\t\t\t\t\t<a id=\"deal\" class=\"sitebtn label_default deal-btn\">거래신청</a>\r\n");
      out.write("\t\t\t\t\t<a id=\"pick\" class=\"sitebtn\">찜하기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"product_content\">\r\n");
      out.write("\t\t<h4>상세 설명</h4>\r\n");
      out.write("\t\t<div class=\"product_content_txt\">\r\n");
      out.write("\t\t\t");
      out.print(gvo.getGcontents() );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"product_content_btn\">\t\r\n");

		String mnum = gvo.getMnum();

		String url;
		if(gsort.equals("1")){
			url="/spw/generalSList.spw";
		}else{
			url="/spw/generalPList.spw";
		}
		if(mnum.equals(sessionNum)){

      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"/spw/generalUpdateForm.spw?gnum=");
      out.print(gvo.getGnum() );
      out.write("\" class=\"sitebtn\">수정</a>\r\n");
      out.write("\t\t\t\t<a href=\"/spw/generalDeleteOK.spw?gnum=");
      out.print(gvo.getGnum() );
      out.write("&gsort=");
      out.print(gvo.getGsort() );
      out.write("\" class=\"sitebtn\">삭제</a>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(url );
      out.write("\" class=\"sitebtn\">목록</a>\r\n");

		}else{

      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(url );
      out.write("\" class=\"sitebtn\">목록</a>\t\t\r\n");

		}

      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"dim-layer\">\r\n");
      out.write("    <div class=\"dimBg\"></div>\r\n");
      out.write("    <div id=\"dealLayer\" class=\"pop-layer\">\r\n");
      out.write("        <div class=\"pop-container\">\r\n");
      out.write("            <div class=\"pop-conts\">\r\n");
      out.write("                <!--content //-->\r\n");
      out.write("                <h3>거래신청 - 전화번호입력란</h3>\r\n");
      out.write("                <div class=\"phoneForm\">\r\n");
      out.write("                \t전화번호 : <input type=\"text\" name=\"phone0\" id=\"phone0\" size=\"3\"/>-\r\n");
      out.write("                \t\t\t <input type=\"text\" name=\"phone1\" id=\"phone1\" size=\"4\"/>-\r\n");
      out.write("                \t\t\t <input type=\"text\" name=\"phone2\" id=\"phone2\" size=\"4\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-r\"> \r\n");
      out.write("                \t<input type=\"hidden\" name=\"mnum\" id=\"mnum\" value=\"");
      out.print(gvo.getMnum() );
      out.write("\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"gnum\" id=\"gnum\" value=\"");
      out.print(gvo.getGnum() );
      out.write("\">\r\n");
      out.write("                \t<input type=\"submit\" name=\"dealFunc\" id=\"dealFunc\" value=\"전송\"/>\r\n");
      out.write("                \t<input type=\"button\" class=\"btn-layerClose\" value=\"취소\"/>\r\n");
      out.write("                    <a href=\"#\" class=\"btn-layerClose\">Close</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--// content-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\t\r\n");
	
	}

      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/comment/list.spw" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("cpnum", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 하단바 -->\r\n");
      out.write("<footer id=\"footerarea\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t[안내]\r\n");
      out.write("\t\t\t<br>아이콘 제작자 :\r\n");
      out.write("\t\t\t<a href=\"http://www.freepik.com/\" title=\"Freepik\">Freepik</a>\r\n");
      out.write("\t\t\tfrom\r\n");
      out.write("\t\t\t<a href=\"https://www.flaticon.com/kr/\" title=\"Flaticon\"> www.flaticon.com</a><br>\r\n");
      out.write("\t\t\t이 사이트는 실제 서비스가 되지 않는 교육실습용 사이트입니다.<br>\r\n");
      out.write("\t\t\t메인 배너 출처 :\r\n");
      out.write("\t\t\t<a href=\"https://m.bunjang.co.kr\">번개장터</a><br>\r\n");
      out.write("\t\t\t고객센터문의 :\r\n");
      out.write("\t\t\tcom.sajapanda@gmail.com\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
